name: Build Readme

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: "net5.0"
      - name: Render Readme
        working-directory: ALG
        run: dotnet run
      
